--- #YAML:1.0
name:                Cache-Historical
version:             0.02
abstract:            Cache historical values
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBD::SQLite:                   1.14
    DBI:                           0
    Log::Log4perl:                 1
    Rose::DB:                      0.735
    Rose::DB::Object::Loader:      0.764
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
